language: python
python:
  - "3.6"

before_install:
- git clone --depth 1 https://github.com/KiCad/kicad-library-utils /home/travis/build/kicad-library-utils
- git clone --depth 1 https://github.com/KiCad/kicad-symbols /home/travis/build/kicad-library-old
- git clone --depth 1 https://github.com/KiCad/kicad-footprints /home/travis/build/kicad-footprints

script:
- cd /home/travis/build/kicad-library-utils/schlib
- python comparelibs.py --new $TRAVIS_BUILD_DIR/*.lib --old /home/travis/build/kicad-library-old/*.lib --check -v --footprints /home/travis/build/kicad-footprints 
- python /home/travis/build/kicad-library-utils/check_lib_table.py $TRAVIS_BUILD_DIR/*.lib --table $TRAVIS_BUILD_DIR/sym-lib-table
